UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Длина шины, см', property_value = '35' WHERE id = 1;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Мощность (л.с.)', property_value = '1.63' WHERE id = 2;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Объем двигателя, куб.см', property_value = '37.2' WHERE id = 3;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Мощность (кВт)', property_value = '1.2' WHERE id = 4;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Класс пилы', property_value = 'бытовая' WHERE id = 5;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Емкость топливного бака, л', property_value = '0.3' WHERE id = 6;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Объем масляного бака, л', property_value = '0.17' WHERE id = 7;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Уровень шума, дБ(А)', property_value = '114' WHERE id = 8;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Вес, кг', property_value = '4.5' WHERE id = 9;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Работа одной рукой', property_value = 'нет' WHERE id = 10;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Легкий запуск', property_value = 'нет' WHERE id = 11;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Мах скорость вращения цепи, м/с', property_value = '21.9' WHERE id = 12;
UPDATE markeshop.product_properties SET product_id = 1, property_name = 'Обороты холостого хода, об/мин', property_value = '3000' WHERE id = 13;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Длина шины, см', property_value = '40' WHERE id = 14;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Мощность (л.с.)', property_value = '2.5' WHERE id = 15;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Объем двигателя, куб.см', property_value = '42' WHERE id = 16;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Мощность (кВт)', property_value = '1.9' WHERE id = 17;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Класс пилы', property_value = 'бытовая' WHERE id = 18;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Емкость топливного бака, л', property_value = '0.37' WHERE id = 19;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Объем масляного бака, л', property_value = '0.19' WHERE id = 20;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Вес, кг', property_value = '4.7' WHERE id = 21;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Работа одной рукой', property_value = 'нет' WHERE id = 22;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Легкий запуск', property_value = 'есть' WHERE id = 23;
UPDATE markeshop.product_properties SET product_id = 2, property_name = 'Обороты холостого хода, об/мин', property_value = '3100' WHERE id = 24;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Длина шины, см', property_value = '50' WHERE id = 25;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Мощность (л.с.)', property_value = '4.5' WHERE id = 26;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Объем двигателя, куб.см', property_value = '58' WHERE id = 27;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Мощность (кВт)', property_value = '3.3' WHERE id = 28;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Класс пилы', property_value = 'полупрофессиональная' WHERE id = 29;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Емкость топливного бака, л', property_value = '0.57' WHERE id = 30;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Объем масляного бака, л', property_value = '0.55' WHERE id = 31;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Уровень шума, дБ(А)', property_value = '98' WHERE id = 32;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Вес, кг', property_value = '6.72' WHERE id = 33;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Работа одной рукой', property_value = 'нет' WHERE id = 34;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Легкий запуск', property_value = 'есть' WHERE id = 35;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Мах скорость вращения цепи, м/с', property_value = '21' WHERE id = 36;
UPDATE markeshop.product_properties SET product_id = 3, property_name = 'Обороты холостого хода, об/мин', property_value = '2850' WHERE id = 37;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Длина шины, см', property_value = '40' WHERE id = 38;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Мощность (л.с.)', property_value = '3.1' WHERE id = 39;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Объем двигателя, куб.см', property_value = '45.2' WHERE id = 40;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Мощность (кВт)', property_value = '2.31' WHERE id = 41;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Класс пилы', property_value = 'полупрофессиональная' WHERE id = 42;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Емкость топливного бака, л', property_value = '0.55' WHERE id = 43;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Объем масляного бака, л', property_value = '0.31' WHERE id = 44;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Уровень шума, дБ(А)', property_value = '106' WHERE id = 45;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Вес, кг', property_value = '6.3' WHERE id = 46;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Работа одной рукой', property_value = '20' WHERE id = 47;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Легкий запуск', property_value = '3150' WHERE id = 48;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Мах скорость вращения цепи, м/с', property_value = 'нет' WHERE id = 49;
UPDATE markeshop.product_properties SET product_id = 4, property_name = 'Обороты холостого хода, об/мин', property_value = 'нет' WHERE id = 50;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Длина шины, см', property_value = '40' WHERE id = 51;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Мощность (л.с.)', property_value = '2' WHERE id = 52;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Объем двигателя, куб.см', property_value = '38' WHERE id = 53;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Мощность (кВт)', property_value = '1.5' WHERE id = 54;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Класс пилы', property_value = 'бытовая' WHERE id = 55;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Емкость топливного бака, л', property_value = '0.31' WHERE id = 56;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Объем масляного бака, л', property_value = '0.21' WHERE id = 57;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Уровень шума, дБ(А)', property_value = '113' WHERE id = 58;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Вес, кг', property_value = '4.85' WHERE id = 59;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Работа одной рукой', property_value = 'нет' WHERE id = 60;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Легкий запуск', property_value = 'есть' WHERE id = 61;
UPDATE markeshop.product_properties SET product_id = 5, property_name = 'Обороты холостого хода, об/мин', property_value = '3000' WHERE id = 62;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Длина шины, см', property_value = '45' WHERE id = 63;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Мощность (л.с.)', property_value = '2.85' WHERE id = 64;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Объем двигателя, куб.см', property_value = '51.2' WHERE id = 65;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Мощность (кВт)', property_value = '2.2' WHERE id = 66;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Класс пилы', property_value = 'бытовая' WHERE id = 67;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Емкость топливного бака, л', property_value = '0.67' WHERE id = 68;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Объем масляного бака, л', property_value = '0.35' WHERE id = 69;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Уровень шума, дБ(А)', property_value = '112' WHERE id = 70;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Вес, кг', property_value = '6.7' WHERE id = 71;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Работа одной рукой', property_value = 'нет' WHERE id = 72;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Легкий запуск', property_value = 'нет' WHERE id = 73;
UPDATE markeshop.product_properties SET product_id = 6, property_name = 'Обороты холостого хода, об/мин', property_value = '2900' WHERE id = 74;
UPDATE markeshop.product_properties SET product_id = 7, property_name = 'Тип', property_value = 'аккумуляторный' WHERE id = 75;
UPDATE markeshop.product_properties SET product_id = 7, property_name = 'Функции', property_value = 'обдув' WHERE id = 76;
UPDATE markeshop.product_properties SET product_id = 7, property_name = 'Вес, кг', property_value = '1.73' WHERE id = 77;
UPDATE markeshop.product_properties SET product_id = 7, property_name = 'Ранцевый', property_value = 'нет' WHERE id = 78;
UPDATE markeshop.product_properties SET product_id = 7, property_name = 'Время заряда, ч', property_value = '2' WHERE id = 79;
UPDATE markeshop.product_properties SET product_id = 7, property_name = 'Емкость аккумулятора, А*ч', property_value = '1.5' WHERE id = 80;
UPDATE markeshop.product_properties SET product_id = 7, property_name = 'Напряжение аккумулятора, В', property_value = '18' WHERE id = 81;
UPDATE markeshop.product_properties SET product_id = 7, property_name = 'Тип аккумулятора', property_value = 'Li-Ion' WHERE id = 82;
UPDATE markeshop.product_properties SET product_id = 7, property_name = 'Max скорость воздуха, м/с', property_value = '58' WHERE id = 83;
UPDATE markeshop.product_properties SET product_id = 7, property_name = 'Мусоросборник', property_value = 'нет' WHERE id = 84;
UPDATE markeshop.product_properties SET product_id = 8, property_name = 'Тип', property_value = 'бензиновый' WHERE id = 85;
UPDATE markeshop.product_properties SET product_id = 8, property_name = 'Функции', property_value = '0.75' WHERE id = 86;
UPDATE markeshop.product_properties SET product_id = 8, property_name = 'Мощность (л.с.), л.с.', property_value = '1' WHERE id = 87;
UPDATE markeshop.product_properties SET product_id = 8, property_name = 'Max объем воздуха, куб.м/ч', property_value = '612' WHERE id = 88;
UPDATE markeshop.product_properties SET product_id = 8, property_name = 'Функции', property_value = 'обдув, измельчение, всасывание' WHERE id = 89;
UPDATE markeshop.product_properties SET product_id = 8, property_name = 'Вес, кг', property_value = '7.8' WHERE id = 90;
UPDATE markeshop.product_properties SET product_id = 8, property_name = 'Ранцевый', property_value = 'нет' WHERE id = 91;
UPDATE markeshop.product_properties SET product_id = 8, property_name = 'Тактность двигателя', property_value = '2-х тактный' WHERE id = 92;
UPDATE markeshop.product_properties SET product_id = 8, property_name = 'Объем двигателя, куб.см', property_value = '26' WHERE id = 93;
UPDATE markeshop.product_properties SET product_id = 8, property_name = 'Объем бака, л', property_value = '0.5' WHERE id = 94;
UPDATE markeshop.product_properties SET product_id = 9, property_name = 'Тип', property_value = 'электрический' WHERE id = 95;
UPDATE markeshop.product_properties SET product_id = 9, property_name = 'Мощность (кВт), кВт', property_value = '0.6' WHERE id = 96;
UPDATE markeshop.product_properties SET product_id = 9, property_name = 'Max объем воздуха, куб.м/ч', property_value = '210' WHERE id = 97;
UPDATE markeshop.product_properties SET product_id = 9, property_name = 'Функции', property_value = 'обдув, всасывание' WHERE id = 98;
UPDATE markeshop.product_properties SET product_id = 9, property_name = 'Вес, кг', property_value = '1.6' WHERE id = 99;
UPDATE markeshop.product_properties SET product_id = 9, property_name = 'Ранцевый', property_value = 'нет' WHERE id = 100;
UPDATE markeshop.product_properties SET product_id = 9, property_name = 'Max скорость воздуха, м/с', property_value = '58' WHERE id = 101;
UPDATE markeshop.product_properties SET product_id = 9, property_name = 'Мусоросборник', property_value = 'есть' WHERE id = 102;
UPDATE markeshop.product_properties SET product_id = 9, property_name = 'Габариты, мм', property_value = '470х225' WHERE id = 103;