UPDATE markeshop.product_category SET product_id = 1, category_id = 1;
UPDATE markeshop.product_category SET product_id = 2, category_id = 1;
UPDATE markeshop.product_category SET product_id = 3, category_id = 1;
UPDATE markeshop.product_category SET product_id = 4, category_id = 1;
UPDATE markeshop.product_category SET product_id = 5, category_id = 1;
UPDATE markeshop.product_category SET product_id = 6, category_id = 1;
UPDATE markeshop.product_category SET product_id = 7, category_id = 2;
UPDATE markeshop.product_category SET product_id = 8, category_id = 2;
UPDATE markeshop.product_category SET product_id = 9, category_id = 2;